apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-mongo
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-host
spec:
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: "/home/rajan/Development/Mongo/PersistenceNew"
    type: DirectoryOrCreate
  storageClassName: my-local-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-mongo
spec:
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/rajan/Development/Mongo/PersistenceNew2"
    type: DirectoryOrCreate
  storageClassName: local-mongo