apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 200
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 0.5k
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1
#          kind: Ingress
#          name: main-route
#        target:
#          type: Value
#          value: 1k

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: position-tracker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: position-tracker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 200
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 0.5k
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1
#          kind: Ingress
#          name: main-route
#        target:
#          type: Value
#          value: 1k

---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: webapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapp-angular
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 200
    - type: Pods
      pods:
        metric:
          name: packets-per-second
        target:
          type: AverageValue
          averageValue: 0.5k
#    - type: Object
#      object:
#        metric:
#          name: requests-per-second
#        describedObject:
#          apiVersion: networking.k8s.io/v1
#          kind: Ingress
#          name: main-route
#        target:
#          type: Value
#          value: