apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-cron-job
spec: # cron
  jobTemplate:
    spec: # job
      template:
        spec: # pod
          containers:
            - name: cron-job
              image: python:rc-alpine
              command:
                - "python"
              args:
                - "-c"
                - "import time; print('starting'); time.sleep(30); print('done')"
          restartPolicy: Never
      backoffLimit: 2
  schedule: "* * * * *" # every minute