# Active Mq
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: richardchesterwood/k8s-fleetman-queue:resources
          resources:
            requests:
              cpu: 70m
              memory: 300Mi
#            limits:
#              cpu: 300m
#              memory: 70Mi


---

# Api-Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: richardchesterwood/k8s-fleetman-api-gateway:resources
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: 60m
              memory: 300Mi
            limits:
              cpu: 900m
              memory: 700Mi
          envFrom:
            - configMapRef:
                name: production-env



---

# Position Simulator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-simulator
  template:
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
        - name: position-simulation
          image: richardchesterwood/k8s-fleetman-position-simulator:resources
          resources:
            requests:
              cpu: 30m
              memory: 250Mi
#            limits:
#              cpu: 200m
#              memory: 60Mi


#          env:
#            - name: SPRING_PROFILES_ACTIVE
#              value: production-microservice
          envFrom:
            - configMapRef:
                name: production-env

---

# Position Tracker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
  template:
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
        - name: position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:resources
          readinessProbe:
            httpGet:
              path: /history/City Truck
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          resources:
            requests:
              cpu: 60m
              memory: 350Mi
#            limits:
#              cpu: 300m
#              memory: 60Mi

          envFrom:
            - configMapRef:
                name: production-env


---

# Webapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-angular
  template:
    metadata:
      labels:
        app: webapp-angular
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release2
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
            limits:
              cpu: 200m
              memory: 300Mi

          envFrom:
            - configMapRef:
                name: production-env


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-database
  template:
    metadata:
      labels:
        app: history-database
    spec:
      containers:
        - name: mongo
          image: mongo:3.6.5-jessie
          volumeMounts:
            - mountPath: /data/db
              name: mongo-persistence-storage
          resources:
            requests:
              memory: 300Mi
              cpu: 1000m
#            limits:
#              memory: "500Mi"
#              cpu: "500m"
      volumes:
        - name: mongo-persistence-storage
          persistentVolumeClaim:
            claimName: mongo-pvc





